pipeline:
  name: list-docker-images
  identifier: list_docker_images
  projectIdentifier: default_project
  orgIdentifier: default

  stages:
    - stage:
        name: List Images
        identifier: list_images
        type: Custom

        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Fetch Docker Images
                  identifier: fetch_images
                  spec:
                    shell: Bash
                    executionTarget:
                      type: Delegate

                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "===== Fetching Docker Images ====="

                          # Replace with your Docker Hub username/org
                          USERNAME="kolleyvenkatesh"

                          echo "Images under $USERNAME:"

                          curl -s "https://hub.docker.com/v2/repositories/$USERNAME/" \
                          | grep -o '"name":"[^"]*' \
                          | cut -d '"' -f4

                          echo "===== Done ====="

        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
